// <auto-generated />
namespace ImageCloudMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class user_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(user_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201806161721266_user_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
