// <auto-generated />
namespace ImageCloudMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class userid_int_toString : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userid_int_toString));
        
        string IMigrationMetadata.Id
        {
            get { return "201806161820285_userid_int_toString"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
