// <auto-generated />
namespace ImageCloudMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class add_parent_folder_to_folder : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_parent_folder_to_folder));
        
        string IMigrationMetadata.Id
        {
            get { return "201806082326304_add_parent_folder_to_folder"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
